### ISSUE TITLE
Application not running on Linux

### ISSUE THREAD

**Issue by omerwax** [IAI-Cyber/TRADES#15]
Failing to launch the application on Ubunto 20.04
![Screenshot from 2021-05-23 09-16-52](https://user-images.githubusercontent.com/23061503/119251014-ba578900-bbac-11eb-93ab-fd077d46d82a.png)

**Comment by ASH-SYSTEMS** [comment]
Linux version can be created successfully using the source code. This was verified on May 30, and an example out is provided in the prerelease of version 3 (version 3.0.0.beta).
The compiled Linux and Mac versions that appear in the releases section may not always work, as sometimes the versions are generated using the Windows version of Eclipse. This is an Eclipse platform bug.
