### ISSUE TITLE
Create a HTML rendering widget

### ISSUE THREAD

**Issue by adaussy** [IAI-Cyber/TRADES#26]
In order to display nice documentation and title in OSCAL we need to create a EEF widget that can renderer HTML.

**Comment by adaussy** [comment]
Done in temporary plugins named org.eclipse.eef.ext.widgets.markup.* and org.eclipse.sirius.*.widgets.markup.
Those plugin are in the process to be contributed to the Eclipse Sirius and Eclipse EEF project. Once integrated and a proper version released, please delete thoses plugin and add the correct feature to the target platform.

**Comment by ASH-SYSTEMS** [comment]
> Done in temporary plugins named org.eclipse.eef.ext.widgets.markup.* and org.eclipse.sirius.*.widgets.markup. Those plugin are in the process to be contributed to the Eclipse Sirius and Eclipse EEF project. Once integrated and a proper version released, please delete thoses plugin and add the correct feature to the target platform.

Can you please inform what are the alternative plugins used in the Eclipse Sirius and EEF proper versions?
