### ISSUE TITLE
The application “Trades.app” can’t be opened on macOS Catalina

### ISSUE THREAD

**Issue by someMonkey** [IAI-Cyber/TRADES#6]
The app Trades_2.5.2.202103110953-macosx.cocoa.x86_64 can’t be opened on macOS Catalina 10.15.7 (19H1030) with the following message on the system logs: "Could not find and/or execute program specified by service: 13: Permission denied: /Applications/Trades.app/Contents/MacOS/trades"

**Comment by adaussy** [comment]
This is a reccurrent problem of Eclipse RCP application which are not built on mac. 

Can you try one of the following workaround and tell me if it fixes the issue please?


* Use the following command to remove the app from the quarantine zone 'xattr -d com.apple.quarantine <name>.app'
* Use the following command 'chmod +x <name>.app/Contents/MacOS/trades'

Regards,

Arthur

**Comment by someMonkey** [comment]
Hi Arthur, thanks a lot for your support! 
Provided by you workaround fixed the issue.
